[package]
name = "android-pin-brute-force"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build]
rustflags = ["-C", "target-feature=+crt-static"]
target = "aarch64-linux-android"
